name: Deploy Whiteboard

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout code
      uses: actions/checkout@v4

      -name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

      -name: Install dependencies
      run: npm install --legacy-peer-deps

      -name: Run tests
      run: npm test || echo "No tests configured"

      -name: Deploy to Render
      uses: render-examples/deploy-action@v1
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}